In [ ]:
# pip install pandas

In [67]:
import pandas as pd

In [68]:
df=pd.read_csv("C:\\Users\\Neha\\Downloads\\sales_customer_analytics.csv")

In [69]:
df.head(10) #head() is used to view the first five rows along with each and every column in the dataset

OrderID   OrderDate  CustomerID CustomerName       City     Product  \
0     1001  2024-01-01         252        Pooja      Delhi      Laptop   
1     1002  2024-01-01         293    Siddharth     Mumbai      Mobile   
2     1003  2024-01-01         215        Megha  Hyderabad      Mobile   
3     1004  2024-01-01         272       Ananya  Hyderabad     Monitor   
4     1005  2024-01-02         261        Rohit    Chennai      Tablet   
5     1006  2024-01-02         221    Siddharth       Pune      Laptop   
6     1007  2024-01-02         283         Riya  Bangalore        Desk   
7     1008  2024-01-03         287        Kavya      Delhi        Desk   
8     1009  2024-01-03         275         Riya  Hyderabad    Keyboard   
9     1010  2024-01-03         275         Isha     Mumbai  Headphones   

      Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
0  Electronics         1       5852         0.10          UPI    Returned   
1  Electronics         1      27922         0.05         Cash   Delivered   
2  Electronics         3      42376         0.15   Debit Card   Cancelled   
3  Electronics         1      61492         0.20          UPI   Delivered   
4  Electronics         1      18306         0.15         Cash   Cancelled   
5  Electronics         3       6444         0.00  Credit Card   Delivered   
6    Furniture         2      54444         0.10          UPI   Cancelled   
7    Furniture         3      59963          NaN  Credit Card   Delivered   
8  Accessories         1      57218         0.15   Debit Card   Delivered   
9  Accessories         1      25044         0.05          UPI   Delivered   

   Rating  
0     5.0  
1     5.0  
2     5.0  
3     3.0  
4     4.0  
5     3.0  
6     2.0  
7     5.0  
8     3.0  
9     NaN

In [70]:
df.tail(10) #tail() is used to view the last 5 rows (default) along with each and every column in the dataset

OrderID   OrderDate  CustomerID CustomerName       City     Product  \
540     1541  2024-06-27         280        Sneha    Chennai        Desk   
541     1542  2024-06-27         202        Rahul  Bangalore      Mobile   
542     1543  2024-06-27         292        Karan     Mumbai      Tablet   
543     1544  2024-06-28         232        Megha       Pune       Chair   
544     1545  2024-06-28         291       Aditya    Chennai       Mouse   
545     1546  2024-06-28         284         Neha      Delhi     Monitor   
546     1547  2024-06-29         224        Pooja      Delhi        Desk   
547     1548  2024-06-29         212        Megha     Mumbai        Desk   
548     1549  2024-06-29         250       Manish    Chennai  Headphones   
549     1550  2024-06-30         235        Megha     Mumbai     Monitor   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
540    Furniture         2      23353         0.20   Debit Card   Delivered   
541  Electronics         4      40496         0.00   Debit Card   Delivered   
542  Electronics         1      52418         0.10         Cash   Delivered   
543    Furniture         1      23708         0.00   Debit Card   Delivered   
544  Accessories         2      10143          NaN         Cash   Delivered   
545  Electronics         1      48761         0.15  Credit Card   Delivered   
546    Furniture         3      10572         0.05   Debit Card   Delivered   
547    Furniture         4      54018          NaN          UPI   Delivered   
548  Accessories         4      45441         0.10  Credit Card   Cancelled   
549  Electronics         1      28342          NaN         Cash   Delivered   

     Rating  
540     3.0  
541     5.0  
542     3.0  
543     5.0  
544     3.0  
545     4.0  
546     5.0  
547     5.0  
548     5.0  
549     3.0

In [71]:
df.info() # info() is used to check for information of the dataframe columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   OrderID       550 non-null    int64  
 1   OrderDate     550 non-null    object 
 2   CustomerID    550 non-null    int64  
 3   CustomerName  550 non-null    object 
 4   City          550 non-null    object 
 5   Product       550 non-null    object 
 6   Category      550 non-null    object 
 7   Quantity      550 non-null    int64  
 8   UnitPrice     550 non-null    int64  
 9   DiscountPct   458 non-null    float64
 10  PaymentMode   550 non-null    object 
 11  OrderStatus   550 non-null    object 
 12  Rating        512 non-null    float64
dtypes: float64(2), int64(4), object(7)
memory usage: 56.0+ KB


In [72]:
df.describe() # describe() returns the statistical summary only for numerical columns

OrderID  CustomerID    Quantity     UnitPrice  DiscountPct  \
count   550.000000  550.000000  550.000000    550.000000   458.000000   
mean   1275.500000  250.258182    2.454545  33071.741818     0.099891   
std     158.915596   29.763651    1.108309  18322.527529     0.069894   
min    1001.000000  201.000000    1.000000   1007.000000     0.000000   
25%    1138.250000  224.000000    1.000000  17455.750000     0.050000   
50%    1275.500000  251.000000    2.000000  33185.000000     0.100000   
75%    1412.750000  275.000000    3.000000  49023.500000     0.150000   
max    1550.000000  300.000000    4.000000  64910.000000     0.200000   

           Rating  
count  512.000000  
mean     3.742188  
std      1.139891  
min      1.000000  
25%      3.000000  
50%      4.000000  
75%      5.000000  
max      5.000000

-OrderId
-orderid feature have **550** values.
-orderid feature mean value **1275.500000** is greater than standard deviation value **158.915596** ,less data variated
-orderid feature **1001** is the minimum value and 1550 is the maximum value in this column.
-orderid 25% of data is below this **1138** 
-orderid 50% of data is below this **1275** 
-orderid 75% of data is below this **1412** 

-OrderDate
-orderdate feature have **550** values
-orderdate feature have **182** unique values
-orderdate **01-01-2024** is the most frequent value in this column ,because it is repeated 4 times. 

-CustomerId
-customerid have **550** values
-customerid  mean value **250.258182** is more than mean value **29.763651**so the data is less variated.
-customerid  **201** is the minimum value and **300** is the maximum value.
-customerid 25% of data is below this **224** 
-customerid 50% of data is below this **251** 
-customerid 75% of data is below this **271** 

-CustomerName
-customername feature have **550** values
-ocustomername feature have **20** unique values
-customername feature **pooja** is the most frequent value in this column ,because it is repeated **37** times. 

-City
-city feature have **550** values.
-city feature have **6** unique values
-city feature **chennai** is the most frequent value in this column ,because it is repeated **102** times. 

-Product
-product feature have **550** values
-poduct feature have **9** unique values
-product feature **chair** is the most frequent value in this column ,because it is repeated **68** times. 

-Category
-category feature have **550** values
-category feature have **3** unique values
-category feature **electronics** is the most frequent value in this column ,because it is repeated **243** times. 

-Quantity
-quantity feature have **550** values
-quantity feature mean value **2.454545** is more than standard deviation value **1.108309** so the data is less variated.
-quantityid 25% of data is below this **1** 
-quantityid 50% of data is below this **2** 
-quantityid 75% of data is below this **3** 

-UnitPrice
-unitprice feature have **550** values
-unitprice feature mean value **33071.741818** is more than standard deviation value **18322.527529** so the data is less variated.
-unitprice feature **1007** is the minimum value and maximum value **64910**
-unitprice 25% of data is below this **17455.750000**
-unitprice 50% of data is below this **33185**
-unitprice 75% of data is below this **49023.500000**

- DiscountPct
-discountpct feature have **550** values
-discountpct feature both the values standard deviation and mean are same or zero
-discountpct feature **0** is the minimum value and maximum value **0**  of this column.
-discountpct 25% of data is below this **0**
-discountpct 50% of data is below this **0**
-discountpct 75% of data is below this **0**

-PaymentMode
-paymentmode feature have **550** values
-paymentmode feature have **4** unique values
-paymentmode feature **upi** is the most frequent value in this column ,because it is repeated **156** times. 

-OrderStatus
-orderstatus feature have **550** values
-orderstatus feature have **3** unique values.
-orderstatus feature **delivered** is the most frequent value in this column,because it is repeated **457** times.

-Rating
-rating feature have **550** values
-rating have mean **3** is greater than standard deviation **1** so the data is less varited.
-rating feature **1** is the minimum value  and maximum value **5**of this column.
-rating 25% of data lies below this **3**
-rating 50% of data lies below this **4**
-rating 75% of data lies below this **5**

-TotalSale
-totalsale feature have **550** values
-totalsale feature have mean **81438.976364** is greater than standard deviation **63585.253514** so the data is less varited.
-totalsale feature **1136** is the minimum value and maximum value **259640** of this column.
-totalsale 25% of data lies below this **32630**
-totalsale 50% of data lies below this  **61669** 
-totalsale 75% of data lies below this **115376.750000** 

-ExactSalesAmount
-exactsalesamount feature have **550** values
-exactsalesamount feature have mean **74457** is greater than standard deviation **58421** so the data is less varited.
-exactsalesamount **1136** is the minimum value and maximum value **244372** of this column.
-exactsalesamount 25% of data lies below this **29283.487500** 
-exactsalesamount  50% of data lies below this **54992.200000** 
-exactsalesamount 75% of data lies below this **106387** 

In [76]:
df.describe(include="all") # describe(include="all") return the statistical summary for all the columns.

OrderID   OrderDate  CustomerID CustomerName     City Product  \
count    550.000000         550  550.000000          550      550     550   
unique          NaN         182         NaN           20        6       9   
top             NaN  2024-01-01         NaN        Pooja  Chennai   Chair   
freq            NaN           4         NaN           37      102      68   
mean    1275.500000         NaN  250.258182          NaN      NaN     NaN   
std      158.915596         NaN   29.763651          NaN      NaN     NaN   
min     1001.000000         NaN  201.000000          NaN      NaN     NaN   
25%     1138.250000         NaN  224.000000          NaN      NaN     NaN   
50%     1275.500000         NaN  251.000000          NaN      NaN     NaN   
75%     1412.750000         NaN  275.000000          NaN      NaN     NaN   
max     1550.000000         NaN  300.000000          NaN      NaN     NaN   

           Category    Quantity     UnitPrice  DiscountPct PaymentMode  \
count           550  550.000000    550.000000   458.000000         550   
unique            3         NaN           NaN          NaN           4   
top     Electronics         NaN           NaN          NaN         UPI   
freq            243         NaN           NaN          NaN         156   
mean            NaN    2.454545  33071.741818     0.099891         NaN   
std             NaN    1.108309  18322.527529     0.069894         NaN   
min             NaN    1.000000   1007.000000     0.000000         NaN   
25%             NaN    1.000000  17455.750000     0.050000         NaN   
50%             NaN    2.000000  33185.000000     0.100000         NaN   
75%             NaN    3.000000  49023.500000     0.150000         NaN   
max             NaN    4.000000  64910.000000     0.200000         NaN   

       OrderStatus      Rating  
count          550  512.000000  
unique           3         NaN  
top      Delivered         NaN  
freq           457         NaN  
mean           NaN    3.742188  
std            NaN    1.139891  
min            NaN    1.000000  
25%            NaN    3.000000  
50%            NaN    4.000000  
75%            NaN    5.000000  
max            NaN    5.000000

In [77]:
df.isna().sum() # isna().sum() is used to get the total count of missing values in each and every column

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
City             0
Product          0
Category         0
Quantity         0
UnitPrice        0
DiscountPct     92
PaymentMode      0
OrderStatus      0
Rating          38
dtype: int64

In [78]:
df.duplicated().sum() # duplicated().sum() is used to get the count of duplicate rows

np.int64(0)

In [79]:
df["DiscountPct"]= df["DiscountPct"].fillna(0)

In [80]:
df["Rating"].fillna(df["Rating"].mean(),inplace=True)

C:\Users\Neha\AppData\Local\Temp\ipykernel_7872\322049203.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Rating"].fillna(df["Rating"].mean(),inplace=True)


In [81]:
df.isna().sum()

OrderID         0
OrderDate       0
CustomerID      0
CustomerName    0
City            0
Product         0
Category        0
Quantity        0
UnitPrice       0
DiscountPct     0
PaymentMode     0
OrderStatus     0
Rating          0
dtype: int64

In [82]:
df.dtypes

OrderID           int64
OrderDate        object
CustomerID        int64
CustomerName     object
City             object
Product          object
Category         object
Quantity          int64
UnitPrice         int64
DiscountPct     float64
PaymentMode      object
OrderStatus      object
Rating          float64
dtype: object

In [83]:
df['OrderDate']=pd.to_datetime(df['OrderDate'])

In [84]:
df.dtypes

OrderID                  int64
OrderDate       datetime64[ns]
CustomerID               int64
CustomerName            object
City                    object
Product                 object
Category                object
Quantity                 int64
UnitPrice                int64
DiscountPct            float64
PaymentMode             object
OrderStatus             object
Rating                 float64
dtype: object

In [85]:
df['TotalSale']=df["Quantity"]*df["UnitPrice"]

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   OrderID       550 non-null    int64         
 1   OrderDate     550 non-null    datetime64[ns]
 2   CustomerID    550 non-null    int64         
 3   CustomerName  550 non-null    object        
 4   City          550 non-null    object        
 5   Product       550 non-null    object        
 6   Category      550 non-null    object        
 7   Quantity      550 non-null    int64         
 8   UnitPrice     550 non-null    int64         
 9   DiscountPct   550 non-null    float64       
 10  PaymentMode   550 non-null    object        
 11  OrderStatus   550 non-null    object        
 12  Rating        550 non-null    float64       
 13  TotalSale     550 non-null    int64         
dtypes: datetime64[ns](1), float64(2), int64(5), object(6)
memory usage: 60.3+ KB


In [87]:
df.head()

OrderID  OrderDate  CustomerID CustomerName       City  Product  \
0     1001 2024-01-01         252        Pooja      Delhi   Laptop   
1     1002 2024-01-01         293    Siddharth     Mumbai   Mobile   
2     1003 2024-01-01         215        Megha  Hyderabad   Mobile   
3     1004 2024-01-01         272       Ananya  Hyderabad  Monitor   
4     1005 2024-01-02         261        Rohit    Chennai   Tablet   

      Category  Quantity  UnitPrice  DiscountPct PaymentMode OrderStatus  \
0  Electronics         1       5852         0.10         UPI    Returned   
1  Electronics         1      27922         0.05        Cash   Delivered   
2  Electronics         3      42376         0.15  Debit Card   Cancelled   
3  Electronics         1      61492         0.20         UPI   Delivered   
4  Electronics         1      18306         0.15        Cash   Cancelled   

   Rating  TotalSale  
0     5.0       5852  
1     5.0      27922  
2     5.0     127128  
3     3.0      61492  
4     4.0      18306

In [88]:
df['ExactSalesAmount']=df['TotalSale']*(1-df['DiscountPct'])

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   OrderID           550 non-null    int64         
 1   OrderDate         550 non-null    datetime64[ns]
 2   CustomerID        550 non-null    int64         
 3   CustomerName      550 non-null    object        
 4   City              550 non-null    object        
 5   Product           550 non-null    object        
 6   Category          550 non-null    object        
 7   Quantity          550 non-null    int64         
 8   UnitPrice         550 non-null    int64         
 9   DiscountPct       550 non-null    float64       
 10  PaymentMode       550 non-null    object        
 11  OrderStatus       550 non-null    object        
 12  Rating            550 non-null    float64       
 13  TotalSale         550 non-null    int64         
 14  ExactSalesAmount  550 non-

In [90]:
# fetching columns single
df["CustomerName"]

0          Pooja
1      Siddharth
2          Megha
3         Ananya
4          Rohit
         ...    
545         Neha
546        Pooja
547        Megha
548       Manish
549        Megha
Name: CustomerName, Length: 550, dtype: object

In [91]:
#multiple columns
df[["CustomerName","City","Product","Category"]]

CustomerName       City     Product     Category
0          Pooja      Delhi      Laptop  Electronics
1      Siddharth     Mumbai      Mobile  Electronics
2          Megha  Hyderabad      Mobile  Electronics
3         Ananya  Hyderabad     Monitor  Electronics
4          Rohit    Chennai      Tablet  Electronics
..           ...        ...         ...          ...
545         Neha      Delhi     Monitor  Electronics
546        Pooja      Delhi        Desk    Furniture
547        Megha     Mumbai        Desk    Furniture
548       Manish    Chennai  Headphones  Accessories
549        Megha     Mumbai     Monitor  Electronics

[550 rows x 4 columns]

In [92]:
# fetching rows based on indexes-same as python slicing
df[5:10]

OrderID  OrderDate  CustomerID CustomerName       City     Product  \
5     1006 2024-01-02         221    Siddharth       Pune      Laptop   
6     1007 2024-01-02         283         Riya  Bangalore        Desk   
7     1008 2024-01-03         287        Kavya      Delhi        Desk   
8     1009 2024-01-03         275         Riya  Hyderabad    Keyboard   
9     1010 2024-01-03         275         Isha     Mumbai  Headphones   

      Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
5  Electronics         3       6444         0.00  Credit Card   Delivered   
6    Furniture         2      54444         0.10          UPI   Cancelled   
7    Furniture         3      59963         0.00  Credit Card   Delivered   
8  Accessories         1      57218         0.15   Debit Card   Delivered   
9  Accessories         1      25044         0.05          UPI   Delivered   

     Rating  TotalSale  ExactSalesAmount  
5  3.000000      19332           19332.0  
6  2.000000     108888           97999.2  
7  5.000000     179889          179889.0  
8  3.000000      57218           48635.3  
9  3.742188      25044           23791.8

In [93]:
# boolean filtering
df[df["City"]=="Pune"]

OrderID  OrderDate  CustomerID CustomerName  City   Product     Category  \
5       1006 2024-01-02         221    Siddharth  Pune    Laptop  Electronics   
10      1011 2024-01-04         288        Pooja  Pune    Mobile  Electronics   
12      1013 2024-01-04         224        Kavya  Pune    Tablet  Electronics   
18      1019 2024-01-06         230       Aditya  Pune      Desk    Furniture   
21      1022 2024-01-07         264    Siddharth  Pune  Keyboard  Accessories   
..       ...        ...         ...          ...   ...       ...          ...   
526     1527 2024-06-22         269         Riya  Pune    Mobile  Electronics   
532     1533 2024-06-24         219       Manish  Pune  Keyboard  Accessories   
536     1537 2024-06-25         269       Aditya  Pune    Laptop  Electronics   
537     1538 2024-06-26         204        Rahul  Pune     Chair    Furniture   
543     1544 2024-06-28         232        Megha  Pune     Chair    Furniture   

     Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus    Rating  \
5           3       6444         0.00  Credit Card   Delivered  3.000000   
10          3       7531         0.00          UPI   Delivered  5.000000   
12          4      14607         0.20   Debit Card   Cancelled  4.000000   
18          2       6990         0.00          UPI   Delivered  3.000000   
21          1       5635         0.10          UPI   Delivered  5.000000   
..        ...        ...          ...          ...         ...       ...   
526         3      19582         0.05  Credit Card   Delivered  5.000000   
532         3      64836         0.10   Debit Card   Delivered  3.742188   
536         1      30232         0.05  Credit Card   Delivered  4.000000   
537         2      20942         0.00  Credit Card   Delivered  3.000000   
543         1      23708         0.00   Debit Card   Delivered  5.000000   

     TotalSale  ExactSalesAmount  
5        19332           19332.0  
10       22593           22593.0  
12       58428           46742.4  
18       13980           13980.0  
21        5635            5071.5  
..         ...               ...  
526      58746           55808.7  
532     194508          175057.2  
536      30232           28720.4  
537      41884           41884.0  
543      23708           23708.0  

[97 rows x 15 columns]

In [94]:
df[df["OrderStatus"]=="Delivered"]

OrderID  OrderDate  CustomerID CustomerName       City   Product  \
1       1002 2024-01-01         293    Siddharth     Mumbai    Mobile   
3       1004 2024-01-01         272       Ananya  Hyderabad   Monitor   
5       1006 2024-01-02         221    Siddharth       Pune    Laptop   
7       1008 2024-01-03         287        Kavya      Delhi      Desk   
8       1009 2024-01-03         275         Riya  Hyderabad  Keyboard   
..       ...        ...         ...          ...        ...       ...   
544     1545 2024-06-28         291       Aditya    Chennai     Mouse   
545     1546 2024-06-28         284         Neha      Delhi   Monitor   
546     1547 2024-06-29         224        Pooja      Delhi      Desk   
547     1548 2024-06-29         212        Megha     Mumbai      Desk   
549     1550 2024-06-30         235        Megha     Mumbai   Monitor   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
1    Electronics         1      27922         0.05         Cash   Delivered   
3    Electronics         1      61492         0.20          UPI   Delivered   
5    Electronics         3       6444         0.00  Credit Card   Delivered   
7      Furniture         3      59963         0.00  Credit Card   Delivered   
8    Accessories         1      57218         0.15   Debit Card   Delivered   
..           ...       ...        ...          ...          ...         ...   
544  Accessories         2      10143         0.00         Cash   Delivered   
545  Electronics         1      48761         0.15  Credit Card   Delivered   
546    Furniture         3      10572         0.05   Debit Card   Delivered   
547    Furniture         4      54018         0.00          UPI   Delivered   
549  Electronics         1      28342         0.00         Cash   Delivered   

     Rating  TotalSale  ExactSalesAmount  
1       5.0      27922          26525.90  
3       3.0      61492          49193.60  
5       3.0      19332          19332.00  
7       5.0     179889         179889.00  
8       3.0      57218          48635.30  
..      ...        ...               ...  
544     3.0      20286          20286.00  
545     4.0      48761          41446.85  
546     5.0      31716          30130.20  
547     5.0     216072         216072.00  
549     3.0      28342          28342.00  

[457 rows x 15 columns]

In [95]:
# Multiple Conditions
df[(df["City"]=="Pune") & (df["OrderStatus"]=="Delivered")]

OrderID  OrderDate  CustomerID CustomerName  City   Product     Category  \
5       1006 2024-01-02         221    Siddharth  Pune    Laptop  Electronics   
10      1011 2024-01-04         288        Pooja  Pune    Mobile  Electronics   
18      1019 2024-01-06         230       Aditya  Pune      Desk    Furniture   
21      1022 2024-01-07         264    Siddharth  Pune  Keyboard  Accessories   
22      1023 2024-01-08         260       Manish  Pune    Tablet  Electronics   
..       ...        ...         ...          ...   ...       ...          ...   
526     1527 2024-06-22         269         Riya  Pune    Mobile  Electronics   
532     1533 2024-06-24         219       Manish  Pune  Keyboard  Accessories   
536     1537 2024-06-25         269       Aditya  Pune    Laptop  Electronics   
537     1538 2024-06-26         204        Rahul  Pune     Chair    Furniture   
543     1544 2024-06-28         232        Megha  Pune     Chair    Furniture   

     Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus    Rating  \
5           3       6444         0.00  Credit Card   Delivered  3.000000   
10          3       7531         0.00          UPI   Delivered  5.000000   
18          2       6990         0.00          UPI   Delivered  3.000000   
21          1       5635         0.10          UPI   Delivered  5.000000   
22          1      46245         0.05  Credit Card   Delivered  4.000000   
..        ...        ...          ...          ...         ...       ...   
526         3      19582         0.05  Credit Card   Delivered  5.000000   
532         3      64836         0.10   Debit Card   Delivered  3.742188   
536         1      30232         0.05  Credit Card   Delivered  4.000000   
537         2      20942         0.00  Credit Card   Delivered  3.000000   
543         1      23708         0.00   Debit Card   Delivered  5.000000   

     TotalSale  ExactSalesAmount  
5        19332          19332.00  
10       22593          22593.00  
18       13980          13980.00  
21        5635           5071.50  
22       46245          43932.75  
..         ...               ...  
526      58746          55808.70  
532     194508         175057.20  
536      30232          28720.40  
537      41884          41884.00  
543      23708          23708.00  

[82 rows x 15 columns]

In [96]:
# using isin we can check multiple filters
df[df["City"].isin(["Pune","Chennai"])]

OrderID  OrderDate  CustomerID CustomerName     City     Product  \
4       1005 2024-01-02         261        Rohit  Chennai      Tablet   
5       1006 2024-01-02         221    Siddharth     Pune      Laptop   
10      1011 2024-01-04         288        Pooja     Pune      Mobile   
12      1013 2024-01-04         224        Kavya     Pune      Tablet   
13      1014 2024-01-05         203        Pooja  Chennai     Monitor   
..       ...        ...         ...          ...      ...         ...   
539     1540 2024-06-26         224       Manish  Chennai      Laptop   
540     1541 2024-06-27         280        Sneha  Chennai        Desk   
543     1544 2024-06-28         232        Megha     Pune       Chair   
544     1545 2024-06-28         291       Aditya  Chennai       Mouse   
548     1549 2024-06-29         250       Manish  Chennai  Headphones   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
4    Electronics         1      18306         0.15         Cash   Cancelled   
5    Electronics         3       6444         0.00  Credit Card   Delivered   
10   Electronics         3       7531         0.00          UPI   Delivered   
12   Electronics         4      14607         0.20   Debit Card   Cancelled   
13   Electronics         4      36709         0.15   Debit Card   Delivered   
..           ...       ...        ...          ...          ...         ...   
539  Electronics         3      10260         0.10  Credit Card   Delivered   
540    Furniture         2      23353         0.20   Debit Card   Delivered   
543    Furniture         1      23708         0.00   Debit Card   Delivered   
544  Accessories         2      10143         0.00         Cash   Delivered   
548  Accessories         4      45441         0.10  Credit Card   Cancelled   

     Rating  TotalSale  ExactSalesAmount  
4       4.0      18306           15560.1  
5       3.0      19332           19332.0  
10      5.0      22593           22593.0  
12      4.0      58428           46742.4  
13      2.0     146836          124810.6  
..      ...        ...               ...  
539     1.0      30780           27702.0  
540     3.0      46706           37364.8  
543     5.0      23708           23708.0  
544     3.0      20286           20286.0  
548     5.0     181764          163587.6  

[199 rows x 15 columns]

In [97]:
df[df["TotalSale"].between(5000,15000)] #use between for range filter

OrderID  OrderDate  CustomerID CustomerName       City     Product  \
0       1001 2024-01-01         252        Pooja      Delhi      Laptop   
18      1019 2024-01-06         230       Aditya       Pune        Desk   
21      1022 2024-01-07         264    Siddharth       Pune    Keyboard   
58      1059 2024-01-20         202        Priya    Chennai     Monitor   
94      1095 2024-01-31         240        Kunal      Delhi      Tablet   
102     1103 2024-02-03         260        Rohit    Chennai  Headphones   
110     1111 2024-02-06         209        Rahul    Chennai     Monitor   
145     1146 2024-02-17         203    Siddharth      Delhi      Mobile   
161     1162 2024-02-23         296        Pooja       Pune        Desk   
168     1169 2024-02-25         236        Priya     Mumbai     Monitor   
188     1189 2024-03-02         292    Siddharth      Delhi     Monitor   
193     1194 2024-03-04         227        Aarav      Delhi    Keyboard   
194     1195 2024-03-04         262       Manish  Bangalore     Monitor   
197     1198 2024-03-05         270       Manish  Hyderabad     Monitor   
202     1203 2024-03-07         237       Vikram  Hyderabad     Monitor   
213     1214 2024-03-11         262        Arjun  Bangalore      Tablet   
229     1230 2024-03-16         297        Megha     Mumbai        Desk   
232     1233 2024-03-17         202        Arjun    Chennai       Mouse   
251     1252 2024-03-23         216       Ananya     Mumbai        Desk   
252     1253 2024-03-24         297    Siddharth      Delhi      Laptop   
256     1257 2024-03-25         280        Pooja     Mumbai        Desk   
260     1261 2024-03-26         259        Pooja    Chennai       Chair   
324     1325 2024-04-16         241         Neha  Hyderabad       Mouse   
338     1339 2024-04-21         248        Rahul  Hyderabad     Monitor   
343     1344 2024-04-23         230        Rohit  Hyderabad      Mobile   
350     1351 2024-04-25         298         Neha  Bangalore        Desk   
427     1428 2024-05-20         214       Vikram     Mumbai      Tablet   
439     1440 2024-05-24         225        Kavya       Pune       Chair   
455     1456 2024-05-30         208        Priya     Mumbai      Tablet   
457     1458 2024-05-30         260        Rahul  Hyderabad     Monitor   
460     1461 2024-05-31         206       Aditya       Pune        Desk   
486     1487 2024-06-09         201        Kavya    Chennai       Chair   
497     1498 2024-06-12         222        Priya       Pune       Mouse   
499     1500 2024-06-13         267        Pooja    Chennai      Mobile   
508     1509 2024-06-16         292        Priya      Delhi       Chair   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
0    Electronics         1       5852         0.10          UPI    Returned   
18     Furniture         2       6990         0.00          UPI   Delivered   
21   Accessories         1       5635         0.10          UPI   Delivered   
58   Electronics         1      14860         0.05         Cash   Delivered   
94   Electronics         1      12355         0.10         Cash   Cancelled   
102  Accessories         1      12982         0.05   Debit Card   Delivered   
110  Electronics         1      11616         0.00         Cash   Delivered   
145  Electronics         3       3841         0.05          UPI   Delivered   
161    Furniture         1       7076         0.15          UPI   Delivered   
168  Electronics         4       2769         0.05          UPI   Delivered   
188  Electronics         2       3840         0.05         Cash   Cancelled   
193  Accessories         1       8643         0.10  Credit Card   Delivered   
194  Electronics         1       7504         0.15   Debit Card   Delivered   
197  Electronics         4       1461         0.15          UPI   Delivered   
202  Electronics         1       6582         0.05  Credit Card   Cancelled   
213  Electronics         1       6248   

In [98]:
df.sort_values("TotalSale")# sorting values default is ascending

OrderID  OrderDate  CustomerID CustomerName       City     Product  \
507     1508 2024-06-16         278        Aarav  Hyderabad     Monitor   
330     1331 2024-04-18         221        Pooja  Bangalore       Mouse   
107     1108 2024-02-05         265        Rahul  Hyderabad      Tablet   
294     1295 2024-04-06         237         Riya      Delhi      Laptop   
198     1199 2024-03-06         272       Nikita  Bangalore        Desk   
..       ...        ...         ...          ...        ...         ...   
464     1465 2024-06-01         299        Rahul      Delhi       Mouse   
420     1421 2024-05-18         257         Neha    Chennai       Mouse   
40      1041 2024-01-14         262       Aditya    Chennai      Laptop   
250     1251 2024-03-23         211       Aditya    Chennai     Monitor   
366     1367 2024-04-30         244        Kunal       Pune  Headphones   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
507  Electronics         1       1136         0.00          UPI   Delivered   
330  Accessories         1       1682         0.10         Cash   Cancelled   
107  Electronics         2       1345         0.00  Credit Card   Cancelled   
294  Electronics         1       2844         0.00          UPI   Delivered   
198    Furniture         3       1007         0.05          UPI   Delivered   
..           ...       ...        ...          ...          ...         ...   
464  Accessories         4      61735         0.10  Credit Card   Delivered   
420  Accessories         4      62642         0.15          UPI   Delivered   
40   Electronics         4      62864         0.10  Credit Card   Delivered   
250  Electronics         4      63310         0.10         Cash   Delivered   
366  Accessories         4      64910         0.10   Debit Card   Delivered   

       Rating  TotalSale  ExactSalesAmount  
507  3.000000       1136           1136.00  
330  4.000000       1682           1513.80  
107  1.000000       2690           2690.00  
294  3.742188       2844           2844.00  
198  2.000000       3021           2869.95  
..        ...        ...               ...  
464  3.000000     246940         222246.00  
420  2.000000     250568         212982.80  
40   3.000000     251456         226310.40  
250  5.000000     253240         227916.00  
366  1.000000     259640         233676.00  

[550 rows x 15 columns]

In [99]:
df.sort_values("TotalSale",ascending=False)

OrderID  OrderDate  CustomerID CustomerName       City     Product  \
366     1367 2024-04-30         244        Kunal       Pune  Headphones   
250     1251 2024-03-23         211       Aditya    Chennai     Monitor   
40      1041 2024-01-14         262       Aditya    Chennai      Laptop   
420     1421 2024-05-18         257         Neha    Chennai       Mouse   
464     1465 2024-06-01         299        Rahul      Delhi       Mouse   
..       ...        ...         ...          ...        ...         ...   
198     1199 2024-03-06         272       Nikita  Bangalore        Desk   
294     1295 2024-04-06         237         Riya      Delhi      Laptop   
107     1108 2024-02-05         265        Rahul  Hyderabad      Tablet   
330     1331 2024-04-18         221        Pooja  Bangalore       Mouse   
507     1508 2024-06-16         278        Aarav  Hyderabad     Monitor   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
366  Accessories         4      64910         0.10   Debit Card   Delivered   
250  Electronics         4      63310         0.10         Cash   Delivered   
40   Electronics         4      62864         0.10  Credit Card   Delivered   
420  Accessories         4      62642         0.15          UPI   Delivered   
464  Accessories         4      61735         0.10  Credit Card   Delivered   
..           ...       ...        ...          ...          ...         ...   
198    Furniture         3       1007         0.05          UPI   Delivered   
294  Electronics         1       2844         0.00          UPI   Delivered   
107  Electronics         2       1345         0.00  Credit Card   Cancelled   
330  Accessories         1       1682         0.10         Cash   Cancelled   
507  Electronics         1       1136         0.00          UPI   Delivered   

       Rating  TotalSale  ExactSalesAmount  
366  1.000000     259640         233676.00  
250  5.000000     253240         227916.00  
40   3.000000     251456         226310.40  
420  2.000000     250568         212982.80  
464  3.000000     246940         222246.00  
..        ...        ...               ...  
198  2.000000       3021           2869.95  
294  3.742188       2844           2844.00  
107  1.000000       2690           2690.00  
330  4.000000       1682           1513.80  
507  3.000000       1136           1136.00  

[550 rows x 15 columns]

In [100]:
df.sort_values(["City","TotalSale"],ascending=[True,False])

OrderID  OrderDate  CustomerID CustomerName       City     Product  \
201     1202 2024-03-07         262        Sneha  Bangalore  Headphones   
184     1185 2024-03-01         284        Aarav  Bangalore       Chair   
405     1406 2024-05-13         233       Aditya  Bangalore  Headphones   
528     1529 2024-06-23         234         Isha  Bangalore      Laptop   
153     1154 2024-02-20         215        Kavya  Bangalore       Chair   
..       ...        ...         ...          ...        ...         ...   
497     1498 2024-06-12         222        Priya       Pune       Mouse   
460     1461 2024-05-31         206       Aditya       Pune        Desk   
21      1022 2024-01-07         264    Siddharth       Pune    Keyboard   
413     1414 2024-05-16         299        Megha       Pune    Keyboard   
356     1357 2024-04-27         297         Neha       Pune        Desk   

        Category  Quantity  UnitPrice  DiscountPct  PaymentMode OrderStatus  \
201  Accessories         4      55232         0.20  Credit Card   Delivered   
184    Furniture         4      55155         0.15         Cash   Delivered   
405  Accessories         4      54112         0.00         Cash   Delivered   
528  Electronics         4      52293         0.20   Debit Card   Delivered   
153    Furniture         4      48708         0.15         Cash   Delivered   
..           ...       ...        ...          ...          ...         ...   
497  Accessories         1       6008         0.05   Debit Card   Delivered   
460    Furniture         4       1470         0.15         Cash   Delivered   
21   Accessories         1       5635         0.10          UPI   Delivered   
413  Accessories         2       1687         0.10   Debit Card   Delivered   
356    Furniture         1       3057         0.20          UPI   Cancelled   

     Rating  TotalSale  ExactSalesAmount  
201     5.0     220928          176742.4  
184     2.0     220620          187527.0  
405     4.0     216448          216448.0  
528     4.0     209172          167337.6  
153     5.0     194832          165607.2  
..      ...        ...               ...  
497     5.0       6008            5707.6  
460     2.0       5880            4998.0  
21      5.0       5635            5071.5  
413     4.0       3374            3036.6  
356     5.0       3057            2445.6  

[550 rows x 15 columns]

In [101]:
# Apply()-row-wise

def discount_label(x):
    if x==0:
        return "Nodiscount"
    elif x<=0.10:
        return "Low Discount"
    else:
        return "High Discount"
df["DiscountCategory"]=df["DiscountPct"].apply(discount_label)

In [102]:
df.head()

OrderID  OrderDate  CustomerID CustomerName       City  Product  \
0     1001 2024-01-01         252        Pooja      Delhi   Laptop   
1     1002 2024-01-01         293    Siddharth     Mumbai   Mobile   
2     1003 2024-01-01         215        Megha  Hyderabad   Mobile   
3     1004 2024-01-01         272       Ananya  Hyderabad  Monitor   
4     1005 2024-01-02         261        Rohit    Chennai   Tablet   

      Category  Quantity  UnitPrice  DiscountPct PaymentMode OrderStatus  \
0  Electronics         1       5852         0.10         UPI    Returned   
1  Electronics         1      27922         0.05        Cash   Delivered   
2  Electronics         3      42376         0.15  Debit Card   Cancelled   
3  Electronics         1      61492         0.20         UPI   Delivered   
4  Electronics         1      18306         0.15        Cash   Cancelled   

   Rating  TotalSale  ExactSalesAmount DiscountCategory  
0     5.0       5852            5266.8     Low Discount  
1     5.0      27922           26525.9     Low Discount  
2     5.0     127128          108058.8    High Discount  
3     3.0      61492           49193.6    High Discount  
4     4.0      18306           15560.1    High Discount

In [103]:
# map()-maps the specified value to the given value

city_region={
    "Pune":"West",
    "Mumbai":"West",
    "Delhi":"North",
    "Banglore":"South",
    "Hyderabad":"South",
    "Chennai":"South"}
df["Region"]=df["City"].map(city_region)

In [104]:
df.head()

OrderID  OrderDate  CustomerID CustomerName       City  Product  \
0     1001 2024-01-01         252        Pooja      Delhi   Laptop   
1     1002 2024-01-01         293    Siddharth     Mumbai   Mobile   
2     1003 2024-01-01         215        Megha  Hyderabad   Mobile   
3     1004 2024-01-01         272       Ananya  Hyderabad  Monitor   
4     1005 2024-01-02         261        Rohit    Chennai   Tablet   

      Category  Quantity  UnitPrice  DiscountPct PaymentMode OrderStatus  \
0  Electronics         1       5852         0.10         UPI    Returned   
1  Electronics         1      27922         0.05        Cash   Delivered   
2  Electronics         3      42376         0.15  Debit Card   Cancelled   
3  Electronics         1      61492         0.20         UPI   Delivered   
4  Electronics         1      18306         0.15        Cash   Cancelled   

   Rating  TotalSale  ExactSalesAmount DiscountCategory Region  
0     5.0       5852            5266.8     Low Discount  North  
1     5.0      27922           26525.9     Low Discount   West  
2     5.0     127128          108058.8    High Discount  South  
3     3.0      61492           49193.6    High Discount  South  
4     4.0      18306           15560.1    High Discount  South

In [105]:
df["City"].unique() # unique is used to get the unique value in the column.

array(['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Pune', 'Bangalore'],
      dtype=object)

In [106]:
df["City"].nunique()# nunique is used to get the number of uinque value in the column.

6

In [107]:
df["City"].value_counts() # value_count is used to get the total count for each unique value in the column.

City
Chennai      102
Pune          97
Delhi         95
Bangalore     93
Mumbai        82
Hyderabad     81
Name: count, dtype: int64

# ASSIGNMENT

# 1.Load the dataset into a Pandas DataFrame.

In [109]:
df=pd.read_csv("C:\\Users\\Neha\\Downloads\\edtech_student_learning_data.csv")

# 2.Display the first 10 records of the dataset.

In [110]:
df.head(10)

student_id student_name  gender       city enrollment_date          course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25   Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29         AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05    Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09         AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03   Generative AI   
5        1006    Student_6  Female       Pune      2024-09-18   Generative AI   
6        1007    Student_7    Male     Mumbai      2024-02-22  Data Analytics   
7        1008    Student_8    Male    Chennai      2024-07-23    Data Science   
8        1009    Student_9    Male     Mumbai      2024-05-05         AI & ML   
9        1010   Student_10  Female      Delhi      2024-08-22  Data Analytics   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  \
0    Weekday             120                108              59   
1    Weekday             120                110              57   
2    Weekday             120                 73              49   
3    Weekend             120                 71              64   
4    Weekday             120                101              41   
5    Weekend             120                 79              64   
6    Weekend             120                112              93   
7    Weekend             120                109              72   
8    Weekend             120                 83              75   
9    Weekday             120                118              70   

   assignment_score  project_score  final_rating  learning_hours  \
0                96             66           3.7               6   
1                93             83           4.5              33   
2                72             73           3.6               8   
3                91             81           2.7               5   
4                55             50           2.1              23   
5                98             57           2.6              30   
6                89             94           3.2              29   
7                77             72           4.3              14   
8                61             96           2.6              19   
9                50             89           4.2              26   

  placement_status  feedback_score  attendance_pct  salary_offered  
0           Placed               7           90.00        738963.0  
1       Not Placed               8           91.67             NaN  
2           Placed               5           60.83        501904.0  
3       Not Placed               8           59.17             NaN  
4           Placed               9           84.17        970105.0  
5           Placed               6           65.83        305730.0  
6           Placed               6           93.33        707137.0  
7           Placed               6           90.83       1053790.0  
8           Placed               8           69.17        502210.0  
9       Not Placed               8           98.33             NaN

# 3.Display the last 5 records of the dataset.

In [111]:
df.tail()

student_id student_name  gender       city enrollment_date  \
500        1452  Student_452  Female     Mumbai      2024-03-07   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
502        1210  Student_210    Male  Bangalore      2024-04-04   
503        1178  Student_178    Male      Delhi      2024-01-20   
504        1397  Student_397  Female     Mumbai      2024-05-27   

            course batch_type  total_sessions  sessions_attended  \
500  Generative AI    Weekday             120                 68   
501  Generative AI    Weekday             120                 95   
502        AI & ML    Weekday             120                 75   
503  Generative AI    Weekday             120                 80   
504  Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
500              84                84             58           2.2   
501              92                81             91           3.2   
502              40                84             77           2.4   
503              97                92             66           4.7   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
500              19       Not Placed               8           56.67   
501              16       Not Placed               8           79.17   
502              19           Placed               5           62.50   
503              33           Placed               5           66.67   
504              25           Placed               7           84.17   

     salary_offered  
500             NaN  
501             NaN  
502        750043.0  
503        890611.0  
504       1003022.0

# 4.Check the shape of the dataset.

# 5.Display all column names along with their data types.

In [112]:
df.dtypes

student_id             int64
student_name          object
gender                object
city                  object
enrollment_date       object
course                object
batch_type            object
total_sessions         int64
sessions_attended      int64
avg_quiz_score         int64
assignment_score       int64
project_score          int64
final_rating         float64
learning_hours         int64
placement_status      object
feedback_score         int64
attendance_pct       float64
salary_offered       float64
dtype: object

# 6.Generate summary statistics for all numerical columns.

In [158]:
df.describe()

student_id  total_sessions  sessions_attended  avg_quiz_score  \
count   505.000000           505.0         505.000000      505.000000   
mean   1251.015842           120.0          88.102970       69.601980   
std     144.242011             0.0          17.087232       17.137226   
min    1001.000000           120.0          60.000000       40.000000   
25%    1127.000000           120.0          73.000000       56.000000   
50%    1251.000000           120.0          88.000000       69.000000   
75%    1376.000000           120.0         103.000000       84.000000   
max    1500.000000           120.0         119.000000       99.000000   

       assignment_score  project_score  final_rating  learning_hours  \
count        505.000000     505.000000    505.000000      505.000000   
mean          71.984158      75.287129      3.535220       22.128713   
std           15.777337      14.678794      0.838068        9.924180   
min           45.000000      50.000000      2.000000        5.000000   
25%           58.000000      62.000000      2.800000       14.000000   
50%           72.000000      76.000000      3.535220       23.000000   
75%           86.000000      88.000000      4.200000       31.000000   
max           99.000000      99.000000      5.000000       39.000000   

       feedback_score  attendance_pct  salary_offered  total_score  
count      505.000000      505.000000    3.360000e+02   505.000000  
mean         7.041584       73.419149    7.701324e+05   216.873267  
std          1.370122       14.239418    2.656396e+05    27.491264  
min          5.000000       50.000000    3.005150e+05   140.000000  
25%          6.000000       60.830000    5.442040e+05   198.000000  
50%          7.000000       73.330000    7.788115e+05   217.000000  
75%          8.000000       85.830000    1.003022e+06   235.000000  
max          9.000000       99.170000    1.199092e+06   292.000000

# Interpretations

-StudentId
-studentid have **505** values.
-In studentid mean **1251.015842** is greater than std **144.242011** so ths data is strong and stable.
-In studentid **1001** is the minimum value and **1500** is the maximum value.
-studentid feature have 25% of data lies below this value **1127**.
-studentid have 50% of data lies below this value **1251**.
-studentid have 75% of data lies below this value **1376**.

-Total_Sessions
-totalsessions have **505** values.
-totalsessions mean **120** is greater than std **0** so this data is strong and stable.
-totalsessions **120** is the minimum value and **120** is the maximum value.
-totalsessions have 25% of data lies below this value **120**.
-totalsessions have 50% of data lies below this value **120**.
-totalsessions have 75% of data lies below this value **120**.

-Sessions_Attended
-sessionsattended have 505 values.
-sessionattended mean **88.102970** is greater than std **17.087232** so this data is strong and stable.
-sessionattended **60** is the minimum value and **119** is the maximum value.
-sessionattended have 25% of data lies below this value **73**.
-sessionattended have 50% of data lies below this value **88**.
-sessionattended have 75% of data lies below this value **103**.

-Avg_Quiz_Score
-avgquizscore have 505 values.
-avgquizscore feature have mean **69.601980** is greater than std **17.137226** so this data is strong and stable.
-avgquizscore **40** is the minimum value and **99** is the maximum value.
-avgquizscore have 25% of data lies below this value **56**.
-avgquizscore have 50% of data lies below this value **69**.
-avgquizscore have 75% of data lies below this value **84**.

-Assignment_Score
-assignmentscore have 505 values.
-assignmentscore feature have mean **71.984158** is greater than std **15.777337** so this data is strong and stable.
-assignmentscore **45** is the minimum value and **99** is the maximum value.
-assignmentscore have 25% of data lies below this value **58**.
-assignmentscore have 50% of data lies below this value **72**.
-assignmentscore have 75% of data lies below this value **86**.

-Project_Score
-projectscore have 505 values.
-projectscore feature have mean **75.287129** is greater than std **14.678794** so this data is strong and stable.
-projectscore **50** is the minimum value and **99** is the maximum value.
-projectscore have 25% of data lies below this value **62**.
-projectscore have 50% of data lies below this value **76**.
-projectscore have 75% of data lies below this value **88**.

-Final_Rating
-finalrating have 477 values.39 values are missing.
-finalrating feature have mean **3.535220** is greater than std **0.862365** so this data is strong and stable.
-finalrating **2** is the minimum value and **5** is the maximum value
-finalrating have 25% of data lies below this value **2.800000**.
-finalrating have 50% of data lies below this value **3.600000**.
-finalrating have 75% of data lies below this value **4.300000**.

-Learning_Hours
-learninghours have 505 values.
-learninghours feature have mean **22.128713** is greater than std **9.924180** so this data is strong and stable.
-learninghours **5** is the minimum value and **39** is the maximum value.
-learninghours have 25% of data lies below this value **12**.
-learninghours have 50% of data lies below this value **23**.
-learninghours have 75% of data lies below this value **31**.

-Feedback_Score
-feedbackscore have 505 values.
-feedbackscore feature have mean **7.041584** is greater than std **1.370122** so this data is strong and stable.
-feedbackscore **5** is the minimum value and **9** is the maximum value.
-feedbackscore have 25% of data lies below this value **6**.
-feedbackscore have 50% of data lies below this value **7**.
-feedbackscore have 75% of data lies below this value **8**.

-Attendance_Pct
-attendancepct have 505 values.
-attendancepct feature have mean **73.419149** is greater than std **14.239418* so this data is strong and stable.
-attendancepct **50** is the minimum value and **99** is the maximum value.
-attendancepct have 25% of data lies below this value **60.830000**.
-attendancepct have 50% of data lies below this value **73.330000**.
-attendancepct have 75% of data lies below this value **85.830000**.

-Salary_Offered
-salaryoffered have 3.360000e+05 values.
-salaryoffered feature have mean **7.701324e+05** is greater than std **2.656396e+05** so this data is strong and stable.
-salaryoffered **3.005150e+05** is the minimum value and **1.199092e+06**is the maximum value.
-salaryoffered have 25% of data lies below this value **5.442040e+05**.
-salaryoffered have 50% of data lies below this value **7.788115e+05**.
-salaryoffered have 75% of data lies below this value **1.1003022e+06**.

Total_Score
-totalscore have 505 values.
-totalscore feature have mean **216.873267** is greater than std **27.491264** so this data is strong and stable.
-totalscore **140** is the minimum value and **292** is the maximum value.
-totalscore have 25% of data lies below this value **198**.
-totalscore have 50% of data lies below this value **217**.
-totalscore have 75% of data lies below this value **235**.

# 7.Identify columns that contain missing values

In [114]:
df.isna().sum()

student_id             0
student_name           0
gender                 0
city                   0
enrollment_date        0
course                 0
batch_type             0
total_sessions         0
sessions_attended      0
avg_quiz_score         0
assignment_score       0
project_score          0
final_rating          28
learning_hours         0
placement_status       0
feedback_score         0
attendance_pct         0
salary_offered       169
dtype: int64

# 8.Count the number of missing values in each column. 

In [115]:
df.isna().sum()

student_id             0
student_name           0
gender                 0
city                   0
enrollment_date        0
course                 0
batch_type             0
total_sessions         0
sessions_attended      0
avg_quiz_score         0
assignment_score       0
project_score          0
final_rating          28
learning_hours         0
placement_status       0
feedback_score         0
attendance_pct         0
salary_offered       169
dtype: int64

# 9.Calculate the percentage of missing values in the final_rating column.

# 10.Fill missing values in the final_rating column using the mean.

In [116]:
df["final_rating"].fillna(df["final_rating"].mean(), inplace=True)

C:\Users\Neha\AppData\Local\Temp\ipykernel_7872\4148491563.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["final_rating"].fillna(df["final_rating"].mean(), inplace=True)


# 11.Verify that missing values in final_string are handled.

# 12.Check whether duplicate records exist in the dataset.

In [117]:
df.duplicated().sum()

np.int64(5)

# 13.Count the total number of duplicate rows.

In [118]:
df.duplicated().sum()

np.int64(5)

# 14.Display all duplicate records.

In [119]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
500     True
501     True
502     True
503     True
504     True
Length: 505, dtype: bool

# 15.Remove duplicate records from the dataset.

# 16.Verify the dataset size after removing duplicates.

# 17.Find the number of unique values in the city column.

In [120]:
df["city"].nunique()

6

# 18.Find the number of unique values in the course column.

In [121]:
df["course"].nunique()

4

# 19.Display all unique cities present in the dataset.

In [122]:
df["city"].unique()

array(['Hyderabad', 'Pune', 'Delhi', 'Mumbai', 'Chennai', 'Bangalore'],
      dtype=object)

# 20.Count the number of students in each city.

In [123]:
df["city"].value_counts()

city
Hyderabad    100
Mumbai        95
Pune          87
Bangalore     82
Chennai       73
Delhi         68
Name: count, dtype: int64

# 21.Count the number of students enrolled in each course.

In [124]:
df["course"].value_counts()

course
Data Analytics    143
Data Science      128
AI & ML           126
Generative AI     108
Name: count, dtype: int64

# 22.Identify the course with the highest student enrollment.

# 23.Count the number of students who are placed and not placed.

In [125]:
df[df["placement_status"]=="Placed"].value_counts()

student_id  student_name  gender  city       enrollment_date  course          batch_type  total_sessions  sessions_attended  avg_quiz_score  assignment_score  project_score  final_rating  learning_hours  placement_status  feedback_score  attendance_pct  salary_offered
1210        Student_210   Male    Bangalore  2024-04-04       AI & ML         Weekday     120             75                 40              84                77             2.4           19              Placed            5               62.50           750043.0          2
1178        Student_178   Male    Delhi      2024-01-20       Generative AI   Weekday     120             80                 97              92                66             4.7           33              Placed            5               66.67           890611.0          2
1397        Student_397   Female  Mumbai     2024-05-27       Generative AI   Weekend     120             101                66              83                66             3.6      

# 24.Filter students whose attendance percentage is greater than 80.

In [126]:
df[df["attendance_pct"]>80]

student_id student_name  gender       city enrollment_date  \
0          1001    Student_1    Male  Hyderabad      2024-11-25   
1          1002    Student_2  Female  Hyderabad      2024-09-29   
4          1005    Student_5    Male     Mumbai      2024-02-03   
6          1007    Student_7    Male     Mumbai      2024-02-22   
7          1008    Student_8    Male    Chennai      2024-07-23   
..          ...          ...     ...        ...             ...   
475        1476  Student_476  Female    Chennai      2024-02-05   
477        1478  Student_478  Female     Mumbai      2024-07-06   
481        1482  Student_482  Female     Mumbai      2024-07-15   
488        1489  Student_489    Male    Chennai      2024-10-19   
504        1397  Student_397  Female     Mumbai      2024-05-27   

             course batch_type  total_sessions  sessions_attended  \
0     Generative AI    Weekday             120                108   
1           AI & ML    Weekday             120                110   
4     Generative AI    Weekday             120                101   
6    Data Analytics    Weekend             120                112   
7      Data Science    Weekend             120                109   
..              ...        ...             ...                ...   
475  Data Analytics    Weekday             120                 97   
477         AI & ML    Weekend             120                104   
481   Generative AI    Weekend             120                101   
488   Generative AI    Weekend             120                111   
504   Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
0                59                96             66           3.7   
1                57                93             83           4.5   
4                41                55             50           2.1   
6                93                89             94           3.2   
7                72                77             72           4.3   
..              ...               ...            ...           ...   
475              99                99             94           3.6   
477              88                73             87           3.8   
481              63                56             66           3.6   
488              70                49             75           3.3   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
0                 6           Placed               7           90.00   
1                33       Not Placed               8           91.67   
4                23           Placed               9           84.17   
6                29           Placed               6           93.33   
7                14           Placed               6           90.83   
..              ...              ...             ...             ...   
475              33           Placed               9           80.83   
477              14           Placed               5           86.67   
481              30           Placed               9           84.17   
488              26       Not Placed               7           92.50   
504              25           Placed               7           84.17   

     salary_offered  
0          738963.0  
1               NaN  
4          970105.0  
6          707137.0  
7         1053790.0  
..              ...  
475        855839.0  
477        749813.0  
481        309637.0  
488             NaN  
504       1003022.0  

[181 rows x 18 columns]

# 25.Filter students who attended fewer than 70 sessions.

In [127]:
df[df["total_sessions"]>70]

student_id student_name  gender       city enrollment_date  \
0          1001    Student_1    Male  Hyderabad      2024-11-25   
1          1002    Student_2  Female  Hyderabad      2024-09-29   
2          1003    Student_3    Male       Pune      2024-12-05   
3          1004    Student_4    Male      Delhi      2024-03-09   
4          1005    Student_5    Male     Mumbai      2024-02-03   
..          ...          ...     ...        ...             ...   
500        1452  Student_452  Female     Mumbai      2024-03-07   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
502        1210  Student_210    Male  Bangalore      2024-04-04   
503        1178  Student_178    Male      Delhi      2024-01-20   
504        1397  Student_397  Female     Mumbai      2024-05-27   

            course batch_type  total_sessions  sessions_attended  \
0    Generative AI    Weekday             120                108   
1          AI & ML    Weekday             120                110   
2     Data Science    Weekday             120                 73   
3          AI & ML    Weekend             120                 71   
4    Generative AI    Weekday             120                101   
..             ...        ...             ...                ...   
500  Generative AI    Weekday             120                 68   
501  Generative AI    Weekday             120                 95   
502        AI & ML    Weekday             120                 75   
503  Generative AI    Weekday             120                 80   
504  Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
0                59                96             66           3.7   
1                57                93             83           4.5   
2                49                72             73           3.6   
3                64                91             81           2.7   
4                41                55             50           2.1   
..              ...               ...            ...           ...   
500              84                84             58           2.2   
501              92                81             91           3.2   
502              40                84             77           2.4   
503              97                92             66           4.7   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
0                 6           Placed               7           90.00   
1                33       Not Placed               8           91.67   
2                 8           Placed               5           60.83   
3                 5       Not Placed               8           59.17   
4                23           Placed               9           84.17   
..              ...              ...             ...             ...   
500              19       Not Placed               8           56.67   
501              16       Not Placed               8           79.17   
502              19           Placed               5           62.50   
503              33           Placed               5           66.67   
504              25           Placed               7           84.17   

     salary_offered  
0          738963.0  
1               NaN  
2          501904.0  
3               NaN  
4          970105.0  
..              ...  
500             NaN  
501             NaN  
502        750043.0  
503        890611.0  
504       1003022.0  

[505 rows x 18 columns]

# 26.Filter students with an average quiz score above 85.

In [128]:
df[df["avg_quiz_score"]>85]

student_id student_name  gender       city enrollment_date  \
6          1007    Student_7    Male     Mumbai      2024-02-22   
14         1015   Student_15  Female      Delhi      2024-05-30   
16         1017   Student_17  Female     Mumbai      2024-12-01   
23         1024   Student_24  Female  Hyderabad      2024-12-17   
33         1034   Student_34  Female  Bangalore      2024-04-01   
..          ...          ...     ...        ...             ...   
495        1496  Student_496    Male  Hyderabad      2024-12-29   
496        1497  Student_497    Male  Hyderabad      2024-10-06   
497        1498  Student_498  Female  Bangalore      2024-03-21   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
503        1178  Student_178    Male      Delhi      2024-01-20   

             course batch_type  total_sessions  sessions_attended  \
6    Data Analytics    Weekend             120                112   
14   Data Analytics    Weekend             120                 88   
16          AI & ML    Weekend             120                 98   
23     Data Science    Weekday             120                103   
33    Generative AI    Weekend             120                114   
..              ...        ...             ...                ...   
495    Data Science    Weekday             120                 86   
496   Generative AI    Weekday             120                 61   
497  Data Analytics    Weekday             120                 94   
501   Generative AI    Weekday             120                 95   
503   Generative AI    Weekday             120                 80   

     avg_quiz_score  assignment_score  project_score  final_rating  \
6                93                89             94           3.2   
14               93                71             64           3.9   
16               91                50             68           3.4   
23               92                60             69           4.2   
33               99                98             52           4.3   
..              ...               ...            ...           ...   
495              94                97             57           3.1   
496              88                53             72           3.7   
497              94                53             63           3.4   
501              92                81             91           3.2   
503              97                92             66           4.7   

     learning_hours placement_status  feedback_score  attendance_pct  \
6                29           Placed               6           93.33   
14               29           Placed               7           73.33   
16                5       Not Placed               9           81.67   
23               13       Not Placed               6           85.83   
33               32           Placed               6           95.00   
..              ...              ...             ...             ...   
495              14           Placed               7           71.67   
496              28           Placed               5           50.83   
497              39           Placed               7           78.33   
501              16       Not Placed               8           79.17   
503              33           Placed               5           66.67   

     salary_offered  
6          707137.0  
14        1128411.0  
16              NaN  
23              NaN  
33         572448.0  
..              ...  
495        572544.0  
496        834633.0  
497        333896.0  
501             NaN  
503        890611.0  

[115 rows x 18 columns]

# 27.Filter students enrolled in the Data Science course.

In [129]:
df[df["course"]=="Data Science"]

student_id student_name  gender       city enrollment_date        course  \
2          1003    Student_3    Male       Pune      2024-12-05  Data Science   
7          1008    Student_8    Male    Chennai      2024-07-23  Data Science   
10         1011   Student_11    Male    Chennai      2024-02-12  Data Science   
13         1014   Student_14    Male     Mumbai      2024-09-05  Data Science   
18         1019   Student_19  Female       Pune      2024-01-08  Data Science   
..          ...          ...     ...        ...             ...           ...   
487        1488  Student_488  Female       Pune      2024-09-17  Data Science   
489        1490  Student_490    Male       Pune      2024-09-12  Data Science   
490        1491  Student_491  Female  Bangalore      2024-08-09  Data Science   
495        1496  Student_496    Male  Hyderabad      2024-12-29  Data Science   
498        1499  Student_499    Male     Mumbai      2024-07-20  Data Science   

    batch_type  total_sessions  sessions_attended  avg_quiz_score  \
2      Weekday             120                 73              49   
7      Weekend             120                109              72   
10     Weekday             120                102              53   
13     Weekday             120                109              55   
18     Weekend             120                115              74   
..         ...             ...                ...             ...   
487    Weekday             120                 66              92   
489    Weekend             120                 73              75   
490    Weekday             120                 68              58   
495    Weekday             120                 86              94   
498    Weekday             120                 77              72   

     assignment_score  project_score  final_rating  learning_hours  \
2                  72             73       3.60000               8   
7                  77             72       4.30000              14   
10                 48             61       4.60000              25   
13                 91             96       3.70000              34   
18                 58             78       2.90000              11   
..                ...            ...           ...             ...   
487                65             51       2.20000              27   
489                92             62       4.10000               6   
490                64             96       3.40000              35   
495                97             57       3.10000              14   
498                48             76       3.53522              27   

    placement_status  feedback_score  attendance_pct  salary_offered  
2             Placed               5           60.83        501904.0  
7             Placed               6           90.83       1053790.0  
10        Not Placed               7           85.00             NaN  
13            Placed               6           90.83        645430.0  
18            Placed               8           95.83       1000399.0  
..               ...             ...             ...             ...  
487           Placed               7           55.00        797760.0  
489           Placed               7           60.83        667747.0  
490           Placed               6           56.67       1097955.0  
495           Placed               7           71.67        572544.0  
498           Placed               8           64.17        778646.0  

[128 rows x 18 columns]

# 28.Filter students who are not placed and attended more than 75 sessions.

In [130]:
df[(df["placement_status"]=="Not Placed") & (df["sessions_attended"]>75)]

student_id student_name  gender       city enrollment_date  \
1          1002    Student_2  Female  Hyderabad      2024-09-29   
9          1010   Student_10  Female      Delhi      2024-08-22   
10         1011   Student_11    Male    Chennai      2024-02-12   
15         1016   Student_16    Male     Mumbai      2024-07-01   
16         1017   Student_17  Female     Mumbai      2024-12-01   
..          ...          ...     ...        ...             ...   
469        1470  Student_470  Female  Hyderabad      2024-09-19   
473        1474  Student_474  Female      Delhi      2024-05-26   
480        1481  Student_481  Female     Mumbai      2024-10-29   
488        1489  Student_489    Male    Chennai      2024-10-19   
501        1276  Student_276  Female  Hyderabad      2024-10-15   

             course batch_type  total_sessions  sessions_attended  \
1           AI & ML    Weekday             120                110   
9    Data Analytics    Weekday             120                118   
10     Data Science    Weekday             120                102   
15   Data Analytics    Weekday             120                116   
16          AI & ML    Weekend             120                 98   
..              ...        ...             ...                ...   
469   Generative AI    Weekday             120                111   
473  Data Analytics    Weekend             120                108   
480    Data Science    Weekday             120                 83   
488   Generative AI    Weekend             120                111   
501   Generative AI    Weekday             120                 95   

     avg_quiz_score  assignment_score  project_score  final_rating  \
1                57                93             83           4.5   
9                70                50             89           4.2   
10               53                48             61           4.6   
15               85                59             90           3.6   
16               91                50             68           3.4   
..              ...               ...            ...           ...   
469              73                52             52           3.6   
473              70                66             81           3.7   
480              61                74             89           3.9   
488              70                49             75           3.3   
501              92                81             91           3.2   

     learning_hours placement_status  feedback_score  attendance_pct  \
1                33       Not Placed               8           91.67   
9                26       Not Placed               8           98.33   
10               25       Not Placed               7           85.00   
15               32       Not Placed               7           96.67   
16                5       Not Placed               9           81.67   
..              ...              ...             ...             ...   
469              24       Not Placed               6           92.50   
473              15       Not Placed               6           90.00   
480              36       Not Placed               7           69.17   
488              26       Not Placed               7           92.50   
501              16       Not Placed               8           79.17   

     salary_offered  
1               NaN  
9               NaN  
10              NaN  
15              NaN  
16              NaN  
..              ...  
469             NaN  
473             NaN  
480             NaN  
488             NaN  
501             NaN  

[119 rows x 18 columns]

# 29.Filter students belonging to Pune,Banglore,or Hyderabad.

In [131]:
df[df["city"].isin(["Pune", "Banglore","Hyderabad"])]

student_id student_name  gender       city enrollment_date  \
0          1001    Student_1    Male  Hyderabad      2024-11-25   
1          1002    Student_2  Female  Hyderabad      2024-09-29   
2          1003    Student_3    Male       Pune      2024-12-05   
5          1006    Student_6  Female       Pune      2024-09-18   
18         1019   Student_19  Female       Pune      2024-01-08   
..          ...          ...     ...        ...             ...   
494        1495  Student_495    Male       Pune      2024-12-07   
495        1496  Student_496    Male  Hyderabad      2024-12-29   
496        1497  Student_497    Male  Hyderabad      2024-10-06   
499        1500  Student_500  Female       Pune      2024-06-06   
501        1276  Student_276  Female  Hyderabad      2024-10-15   

            course batch_type  total_sessions  sessions_attended  \
0    Generative AI    Weekday             120                108   
1          AI & ML    Weekday             120                110   
2     Data Science    Weekday             120                 73   
5    Generative AI    Weekend             120                 79   
18    Data Science    Weekend             120                115   
..             ...        ...             ...                ...   
494        AI & ML    Weekend             120                 61   
495   Data Science    Weekday             120                 86   
496  Generative AI    Weekday             120                 61   
499        AI & ML    Weekday             120                 73   
501  Generative AI    Weekday             120                 95   

     avg_quiz_score  assignment_score  project_score  final_rating  \
0                59                96             66           3.7   
1                57                93             83           4.5   
2                49                72             73           3.6   
5                64                98             57           2.6   
18               74                58             78           2.9   
..              ...               ...            ...           ...   
494              69                77             52           4.1   
495              94                97             57           3.1   
496              88                53             72           3.7   
499              57                79             78           3.8   
501              92                81             91           3.2   

     learning_hours placement_status  feedback_score  attendance_pct  \
0                 6           Placed               7           90.00   
1                33       Not Placed               8           91.67   
2                 8           Placed               5           60.83   
5                30           Placed               6           65.83   
18               11           Placed               8           95.83   
..              ...              ...             ...             ...   
494               9           Placed               8           50.83   
495              14           Placed               7           71.67   
496              28           Placed               5           50.83   
499              21           Placed               7           60.83   
501              16       Not Placed               8           79.17   

     salary_offered  
0          738963.0  
1               NaN  
2          501904.0  
5          305730.0  
18        1000399.0  
..              ...  
494        867354.0  
495        572544.0  
496        834633.0  
499       1115331.0  
501             NaN  

[187 rows x 18 columns]

# 30.Filter students enrolled in Ai & Ml or Generative AI courses. 

In [132]:
df[df["course"].isin(["AI & ML", "Generative AI"])]

student_id student_name  gender       city enrollment_date  \
0          1001    Student_1    Male  Hyderabad      2024-11-25   
1          1002    Student_2  Female  Hyderabad      2024-09-29   
3          1004    Student_4    Male      Delhi      2024-03-09   
4          1005    Student_5    Male     Mumbai      2024-02-03   
5          1006    Student_6  Female       Pune      2024-09-18   
..          ...          ...     ...        ...             ...   
500        1452  Student_452  Female     Mumbai      2024-03-07   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
502        1210  Student_210    Male  Bangalore      2024-04-04   
503        1178  Student_178    Male      Delhi      2024-01-20   
504        1397  Student_397  Female     Mumbai      2024-05-27   

            course batch_type  total_sessions  sessions_attended  \
0    Generative AI    Weekday             120                108   
1          AI & ML    Weekday             120                110   
3          AI & ML    Weekend             120                 71   
4    Generative AI    Weekday             120                101   
5    Generative AI    Weekend             120                 79   
..             ...        ...             ...                ...   
500  Generative AI    Weekday             120                 68   
501  Generative AI    Weekday             120                 95   
502        AI & ML    Weekday             120                 75   
503  Generative AI    Weekday             120                 80   
504  Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
0                59                96             66           3.7   
1                57                93             83           4.5   
3                64                91             81           2.7   
4                41                55             50           2.1   
5                64                98             57           2.6   
..              ...               ...            ...           ...   
500              84                84             58           2.2   
501              92                81             91           3.2   
502              40                84             77           2.4   
503              97                92             66           4.7   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
0                 6           Placed               7           90.00   
1                33       Not Placed               8           91.67   
3                 5       Not Placed               8           59.17   
4                23           Placed               9           84.17   
5                30           Placed               6           65.83   
..              ...              ...             ...             ...   
500              19       Not Placed               8           56.67   
501              16       Not Placed               8           79.17   
502              19           Placed               5           62.50   
503              33           Placed               5           66.67   
504              25           Placed               7           84.17   

     salary_offered  
0          738963.0  
1               NaN  
3               NaN  
4          970105.0  
5          305730.0  
..              ...  
500             NaN  
501             NaN  
502        750043.0  
503        890611.0  
504       1003022.0  

[234 rows x 18 columns]

# 31. Filter students whose average quiz score lies between 60 and 80.

In [133]:
df[df["avg_quiz_score"].between(60,80)]

student_id student_name  gender     city enrollment_date          course  \
3          1004    Student_4    Male    Delhi      2024-03-09         AI & ML   
5          1006    Student_6  Female     Pune      2024-09-18   Generative AI   
7          1008    Student_8    Male  Chennai      2024-07-23    Data Science   
8          1009    Student_9    Male   Mumbai      2024-05-05         AI & ML   
9          1010   Student_10  Female    Delhi      2024-08-22  Data Analytics   
..          ...          ...     ...      ...             ...             ...   
489        1490  Student_490    Male     Pune      2024-09-12    Data Science   
493        1494  Student_494  Female    Delhi      2024-12-20   Generative AI   
494        1495  Student_495    Male     Pune      2024-12-07         AI & ML   
498        1499  Student_499    Male   Mumbai      2024-07-20    Data Science   
504        1397  Student_397  Female   Mumbai      2024-05-27   Generative AI   

    batch_type  total_sessions  sessions_attended  avg_quiz_score  \
3      Weekend             120                 71              64   
5      Weekend             120                 79              64   
7      Weekend             120                109              72   
8      Weekend             120                 83              75   
9      Weekday             120                118              70   
..         ...             ...                ...             ...   
489    Weekend             120                 73              75   
493    Weekday             120                 94              75   
494    Weekend             120                 61              69   
498    Weekday             120                 77              72   
504    Weekend             120                101              66   

     assignment_score  project_score  final_rating  learning_hours  \
3                  91             81       2.70000               5   
5                  98             57       2.60000              30   
7                  77             72       4.30000              14   
8                  61             96       2.60000              19   
9                  50             89       4.20000              26   
..                ...            ...           ...             ...   
489                92             62       4.10000               6   
493                88             88       3.90000              36   
494                77             52       4.10000               9   
498                48             76       3.53522              27   
504                83             66       3.60000              25   

    placement_status  feedback_score  attendance_pct  salary_offered  
3         Not Placed               8           59.17             NaN  
5             Placed               6           65.83        305730.0  
7             Placed               6           90.83       1053790.0  
8             Placed               8           69.17        502210.0  
9         Not Placed               8           98.33             NaN  
..               ...             ...             ...             ...  
489           Placed               7           60.83        667747.0  
493           Placed               8           78.33        596618.0  
494           Placed               8           50.83        867354.0  
498           Placed               8           64.17        778646.0  
504           Placed               7           84.17       1003022.0  

[194 rows x 18 columns]

# 32.Filter students whose assignment score lies between 70 and 90.

In [134]:
df[df["assignment_score"].between(70,90)]

student_id student_name  gender       city enrollment_date  \
2          1003    Student_3    Male       Pune      2024-12-05   
6          1007    Student_7    Male     Mumbai      2024-02-22   
7          1008    Student_8    Male    Chennai      2024-07-23   
14         1015   Student_15  Female      Delhi      2024-05-30   
20         1021   Student_21  Female       Pune      2024-07-02   
..          ...          ...     ...        ...             ...   
499        1500  Student_500  Female       Pune      2024-06-06   
500        1452  Student_452  Female     Mumbai      2024-03-07   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
502        1210  Student_210    Male  Bangalore      2024-04-04   
504        1397  Student_397  Female     Mumbai      2024-05-27   

             course batch_type  total_sessions  sessions_attended  \
2      Data Science    Weekday             120                 73   
6    Data Analytics    Weekend             120                112   
7      Data Science    Weekend             120                109   
14   Data Analytics    Weekend             120                 88   
20          AI & ML    Weekday             120                102   
..              ...        ...             ...                ...   
499         AI & ML    Weekday             120                 73   
500   Generative AI    Weekday             120                 68   
501   Generative AI    Weekday             120                 95   
502         AI & ML    Weekday             120                 75   
504   Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
2                49                72             73           3.6   
6                93                89             94           3.2   
7                72                77             72           4.3   
14               93                71             64           3.9   
20               45                83             89           3.7   
..              ...               ...            ...           ...   
499              57                79             78           3.8   
500              84                84             58           2.2   
501              92                81             91           3.2   
502              40                84             77           2.4   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
2                 8           Placed               5           60.83   
6                29           Placed               6           93.33   
7                14           Placed               6           90.83   
14               29           Placed               7           73.33   
20               23       Not Placed               6           85.00   
..              ...              ...             ...             ...   
499              21           Placed               7           60.83   
500              19       Not Placed               8           56.67   
501              16       Not Placed               8           79.17   
502              19           Placed               5           62.50   
504              25           Placed               7           84.17   

     salary_offered  
2          501904.0  
6          707137.0  
7         1053790.0  
14        1128411.0  
20              NaN  
..              ...  
499       1115331.0  
500             NaN  
501             NaN  
502        750043.0  
504       1003022.0  

[189 rows x 18 columns]

# 33.Filter students whose learing hours lie between 10 and 25.

In [135]:
df[df["learning_hours"].between(10,25)]

student_id student_name  gender       city enrollment_date  \
4          1005    Student_5    Male     Mumbai      2024-02-03   
7          1008    Student_8    Male    Chennai      2024-07-23   
8          1009    Student_9    Male     Mumbai      2024-05-05   
10         1011   Student_11    Male    Chennai      2024-02-12   
18         1019   Student_19  Female       Pune      2024-01-08   
..          ...          ...     ...        ...             ...   
499        1500  Student_500  Female       Pune      2024-06-06   
500        1452  Student_452  Female     Mumbai      2024-03-07   
501        1276  Student_276  Female  Hyderabad      2024-10-15   
502        1210  Student_210    Male  Bangalore      2024-04-04   
504        1397  Student_397  Female     Mumbai      2024-05-27   

            course batch_type  total_sessions  sessions_attended  \
4    Generative AI    Weekday             120                101   
7     Data Science    Weekend             120                109   
8          AI & ML    Weekend             120                 83   
10    Data Science    Weekday             120                102   
18    Data Science    Weekend             120                115   
..             ...        ...             ...                ...   
499        AI & ML    Weekday             120                 73   
500  Generative AI    Weekday             120                 68   
501  Generative AI    Weekday             120                 95   
502        AI & ML    Weekday             120                 75   
504  Generative AI    Weekend             120                101   

     avg_quiz_score  assignment_score  project_score  final_rating  \
4                41                55             50           2.1   
7                72                77             72           4.3   
8                75                61             96           2.6   
10               53                48             61           4.6   
18               74                58             78           2.9   
..              ...               ...            ...           ...   
499              57                79             78           3.8   
500              84                84             58           2.2   
501              92                81             91           3.2   
502              40                84             77           2.4   
504              66                83             66           3.6   

     learning_hours placement_status  feedback_score  attendance_pct  \
4                23           Placed               9           84.17   
7                14           Placed               6           90.83   
8                19           Placed               8           69.17   
10               25       Not Placed               7           85.00   
18               11           Placed               8           95.83   
..              ...              ...             ...             ...   
499              21           Placed               7           60.83   
500              19       Not Placed               8           56.67   
501              16       Not Placed               8           79.17   
502              19           Placed               5           62.50   
504              25           Placed               7           84.17   

     salary_offered  
4          970105.0  
7         1053790.0  
8          502210.0  
10              NaN  
18        1000399.0  
..              ...  
499       1115331.0  
500             NaN  
501             NaN  
502        750043.0  
504       1003022.0  

[228 rows x 18 columns]

# 34.Create a new column total_score as the sum of quiz ,assignment,and project scores.

In [136]:
df["total_score"]=df["avg_quiz_score"]+df["assignment_score"]+df["project_score"]
print(df["total_score"])

0      221
1      233
2      194
3      236
4      146
      ... 
500    226
501    264
502    201
503    255
504    215
Name: total_score, Length: 505, dtype: int64


In [137]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  \
0    Weekday             120                108              59   
1    Weekday             120                110              57   
2    Weekday             120                 73              49   
3    Weekend             120                 71              64   
4    Weekday             120                101              41   

   assignment_score  project_score  final_rating  learning_hours  \
0                96             66           3.7               6   
1                93             83           4.5              33   
2                72             73           3.6               8   
3                91             81           2.7               5   
4                55             50           2.1              23   

  placement_status  feedback_score  attendance_pct  salary_offered  \
0           Placed               7           90.00        738963.0   
1       Not Placed               8           91.67             NaN   
2           Placed               5           60.83        501904.0   
3       Not Placed               8           59.17             NaN   
4           Placed               9           84.17        970105.0   

   total_score  
0          221  
1          233  
2          194  
3          236  
4          146

# 35.Create a new column attendance_flag based on attendance percentage.

In [138]:
def percentage(x):
    if x>75:
        return "Good"
    else:
        return "Not Good"
df["attendance_flag"]=df["attendance_pct"].apply(percentage)

In [139]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  \
0    Weekday             120                108              59   
1    Weekday             120                110              57   
2    Weekday             120                 73              49   
3    Weekend             120                 71              64   
4    Weekday             120                101              41   

   assignment_score  project_score  final_rating  learning_hours  \
0                96             66           3.7               6   
1                93             83           4.5              33   
2                72             73           3.6               8   
3                91             81           2.7               5   
4                55             50           2.1              23   

  placement_status  feedback_score  attendance_pct  salary_offered  \
0           Placed               7           90.00        738963.0   
1       Not Placed               8           91.67             NaN   
2           Placed               5           60.83        501904.0   
3       Not Placed               8           59.17             NaN   
4           Placed               9           84.17        970105.0   

   total_score attendance_flag  
0          221            Good  
1          233            Good  
2          194        Not Good  
3          236        Not Good  
4          146            Good

# 36.Create a new column learning_intensity based on learing hours.

In [140]:
def learning_label(x):
    if x>20:
        return "High"
    elif x>=10:
        return "Medium"
    else:
        return "Low"
df["learning_intensity"]=df["learning_hours"].apply(learning_label)

In [141]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   project_score  final_rating  learning_hours  placement_status  \
0             66           3.7               6            Placed   
1             83           4.5              33        Not Placed   
2             73           3.6               8            Placed   
3             81           2.7               5        Not Placed   
4             50           2.1              23            Placed   

  feedback_score  attendance_pct  salary_offered  total_score  \
0              7           90.00        738963.0          221   
1              8           91.67             NaN          233   
2              5           60.83        501904.0          194   
3              8           59.17             NaN          236   
4              9           84.17        970105.0          146   

   attendance_flag learning_intensity  
0             Good                Low  
1             Good               High  
2         Not Good                Low  
3         Not Good                Low  
4             Good               High  

[5 rows x 21 columns]

# 37.Classify students based on total_score using apply().

In [142]:
def classify(x):
    if x >= 150:
        return 'First Class'
    elif x >= 100:
        return 'Pass'
    else:
        return 'Fail'
df["result"]=df["total_score"].apply(classify)

In [143]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   final_rating  learning_hours  placement_status  feedback_score  \
0           3.7               6            Placed               7   
1           4.5              33        Not Placed               8   
2           3.6               8            Placed               5   
3           2.7               5        Not Placed               8   
4           2.1              23            Placed               9   

  attendance_pct  salary_offered  total_score  attendance_flag  \
0          90.00        738963.0          221             Good   
1          91.67             NaN          233             Good   
2          60.83        501904.0          194         Not Good   
3          59.17             NaN          236         Not Good   
4          84.17        970105.0          146             Good   

   learning_intensity       result  
0                 Low  First Class  
1                High  First Class  
2                 Low  First Class  
3                 Low  First Class  
4                High         Pass  

[5 rows x 22 columns]

# 38.Create a placement eligibility column using apply().

In [144]:
def placement_eligibility(x):
    if x >= 150:
        return 'Eligible'
    else:
        return 'Not Eligible'
df["placement_eligibility"]=df["total_score"].apply(placement_eligibility)

In [145]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   learning_hours  placement_status  feedback_score  attendance_pct  \
0               6            Placed               7           90.00   
1              33        Not Placed               8           91.67   
2               8            Placed               5           60.83   
3               5        Not Placed               8           59.17   
4              23            Placed               9           84.17   

  salary_offered  total_score  attendance_flag  learning_intensity  \
0       738963.0          221             Good                 Low   
1            NaN          233             Good                High   
2       501904.0          194         Not Good                 Low   
3            NaN          236         Not Good                 Low   
4       970105.0          146             Good                High   

        result placement_eligibility  
0  First Class              Eligible  
1  First Class              Eligible  
2  First Class              Eligible  
3  First Class              Eligible  
4         Pass          Not Eligible  

[5 rows x 23 columns]

# 39.Map placement_status values to numerical values.

In [146]:
numerical_values={
    "Placed":"01",
    "Not Placed":"02"
}
df["numerical"]=df["placement_status"].map(numerical_values)

In [147]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   placement_status  feedback_score  attendance_pct  salary_offered  \
0            Placed               7           90.00        738963.0   
1        Not Placed               8           91.67             NaN   
2            Placed               5           60.83        501904.0   
3        Not Placed               8           59.17             NaN   
4            Placed               9           84.17        970105.0   

  total_score  attendance_flag  learning_intensity       result  \
0         221             Good                 Low  First Class   
1         233             Good                High  First Class   
2         194         Not Good                 Low  First Class   
3         236         Not Good                 Low  First Class   
4         146             Good                High         Pass   

   placement_eligibility numerical  
0               Eligible        01  
1               Eligible        02  
2               Eligible        01  
3               Eligible        02  
4           Not Eligible        01  

[5 rows x 24 columns]

# 40.Map batch_type values to abbreviated codes.

In [155]:
abbreviated_codes={
    "Weekday":"day",
    "Weekend":"end"
}
df["abbreviated"]=df["batch_type"].map(abbreviated_codes)

In [156]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   attendance_pct  salary_offered  total_score  attendance_flag  \
0           90.00        738963.0          221             Good   
1           91.67             NaN          233             Good   
2           60.83        501904.0          194         Not Good   
3           59.17             NaN          236         Not Good   
4           84.17        970105.0          146             Good   

  learning_intensity       result  placement_eligibility  numerical  \
0                Low  First Class               Eligible         01   
1               High  First Class               Eligible         02   
2                Low  First Class               Eligible         01   
3                Low  First Class               Eligible         02   
4               High         Pass           Not Eligible         01   

   abbreviated gender_values  
0          day             M  
1          day             F  
2          day             M  
3          end             M  
4          day             M  

[5 rows x 26 columns]

# 41.Map gender values to single letter codes.

In [150]:
letter_codes={
    "Male":"M",
    "Female":"F"
}
df["gender_values"]=df["gender"].map(letter_codes)

In [151]:
df.head()

student_id student_name  gender       city enrollment_date         course  \
0        1001    Student_1    Male  Hyderabad      2024-11-25  Generative AI   
1        1002    Student_2  Female  Hyderabad      2024-09-29        AI & ML   
2        1003    Student_3    Male       Pune      2024-12-05   Data Science   
3        1004    Student_4    Male      Delhi      2024-03-09        AI & ML   
4        1005    Student_5    Male     Mumbai      2024-02-03  Generative AI   

  batch_type  total_sessions  sessions_attended  avg_quiz_score  ...  \
0    Weekday             120                108              59  ...   
1    Weekday             120                110              57  ...   
2    Weekday             120                 73              49  ...   
3    Weekend             120                 71              64  ...   
4    Weekday             120                101              41  ...   

   attendance_pct  salary_offered  total_score  attendance_flag  \
0           90.00        738963.0          221             Good   
1           91.67             NaN          233             Good   
2           60.83        501904.0          194         Not Good   
3           59.17             NaN          236         Not Good   
4           84.17        970105.0          146             Good   

  learning_intensity       result  placement_eligibility  numerical  \
0                Low  First Class               Eligible         01   
1               High  First Class               Eligible         02   
2                Low  First Class               Eligible         01   
3                Low  First Class               Eligible         02   
4               High         Pass           Not Eligible         01   

   abbreviated gender_values  
0                          M  
1                          F  
2                          M  
3                          M  
4                          M  

[5 rows x 26 columns]

# 42.Count students under each learning_intensity category.

In [152]:
df["learning_intensity"].value_counts()

learning_intensity
High      281
Medium    152
Low        72
Name: count, dtype: int64

# 43.Calculate the percentage of placement-eligible students.

# 44.Identify the city with the highest number of placed students.

In [162]:
df["city"]=="Placed"

0      False
1      False
2      False
3      False
4      False
       ...  
500    False
501    False
502    False
503    False
504    False
Name: city, Length: 505, dtype: bool

# 45.Compare average total_score for placed and not placed students.

# 46.Identify the top 5 students on total_score.

In [154]:
df["total_score"].head()

0    221
1    233
2    194
3    236
4    146
Name: total_score, dtype: int64